refactor: consolidate

diff --git a/.github/workflows/terraform-module.yml b/.github/workflows/terraform-module.yml
--- a/.github/workflows/terraform-module.yml
+++ b/.github/workflows/terraform-module.yml
@@ -13,6 +13,11 @@ on:
         default: 'latest'
         required: false
         type: string
+      terratest_examples_path:
+        description: 'Path to terratest example directory'
+        default: 'examples'
+        required: false
+        type: string
       tflint_repo:
         description: 'Public repo where tflint config is stored'
         default: 'nuvibit/github-tflint-config'
@@ -36,11 +41,6 @@ on:
       tfsec_version:
         description: 'Tfsec version to use'
         default: 'latest'
-        required: false
-        type: string
-      tfsec_directory:
-        description: 'Directory which should be scanned by tfsec'
-        default: 'examples'
         required: false
         type: string
       commit_user:
@@ -210,12 +210,20 @@ jobs:
         with:
           ref: ${{ github.event.pull_request.head.ref }}
           token: ${{ secrets.GHE_API_TOKEN }}
+
+      - name: Check For Examples
+        run: |
+          if [[ ! -d "./${{ inputs.terratest_examples_path }}" ]]; then
+            echo "could not find examples path '${{ inputs.terratest_examples_path }}' required for terratest"
+            exit 1
+          fi
       
       - name: Run TFSec
         uses: reviewdog/action-tfsec@v1
         id: security
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
+          working_directory: ${{ inputs.terratest_examples_path }}
           tfsec_version: ${{ inputs.tfsec_version }}
           reporter: github-pr-check
           fail_on_error: true
@@ -223,7 +231,6 @@ jobs:
           level: error
           flags: ""
           tfsec_flags: --force-all-dirs
-          working_directory: ${{ inputs.tfsec_directory }}
 
   terratest-run:
     needs:
@@ -246,13 +253,6 @@ jobs:
         with:
           ref: ${{ github.event.pull_request.head.ref }}
           token: ${{ secrets.GHE_API_TOKEN }}
-
-      - name: Check For Examples
-        run: |
-          if [[ ! -d "./${{ inputs.terratest_examples_path }}" ]]; then
-            echo "could not find examples directory '${{ inputs.terratest_examples_path }}' required for terratest"
-            exit 1
-          fi
 
       - name: Setup Go
         uses: actions/setup-go@v3
