feat: consolidate (#7)
* feat: adding license and updating readme

* refactor: adding inputs and consolidating workflows

* fix: updating links

* docs: updating quick start

* fix: removing unused inputs

* refactor: renaming workflow

* fix: updating summary condition and removing obsolete input

* refactor: updating terratest outcome result

* fix: adding continue on error

* docs: updating output

diff --git a/.github/workflows/terraform-module.yml b/.github/workflows/terraform-module.yml
--- a/.github/workflows/terraform-module.yml
+++ b/.github/workflows/terraform-module.yml
@@ -3,14 +3,24 @@ name: TERRAFORM MODULE
 on:
   workflow_call:
     inputs:
+      github_runner:
+        description: 'Name of GitHub-hosted runner or self-hosted runner'
+        default: 'ubuntu-latest'
+        required: false
+        type: string
       tfe_hostname:
         description: 'Hostname for terraform cloud/enterprise'
         default: 'app.terraform.io'
         required: false
         type: string
       terraform_version:
-        description: 'Terraform version used to format code'
+        description: 'Terraform version used for Terratest'
         default: 'latest'
+        required: false
+        type: string
+      terratest_path:
+        description: 'Path to terratest directory'
+        default: 'test'
         required: false
         type: string
       terratest_examples_path:
@@ -53,6 +63,11 @@ on:
         default: 'noreply@github.com'
         required: false
         type: string
+      concurrency_group:
+        description: 'Name of concurrency group to manage concurrent github action runs'
+        default: ${{ github.repository }}/${{ github.event.pull_request.head.ref || github.ref }}
+        required: false
+        type: string
     secrets:
       GHE_API_TOKEN:
         required: true
@@ -74,11 +89,11 @@ on:
         required: false
 
 # Ensures that only one workflow runs at a time
-concurrency: ${{ github.repository }}/${{ github.event.pull_request.head.ref || github.ref }}
+concurrency: ${{ inputs.concurrency_group }}
 
 jobs:
   terraform-fmt:
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.github_runner }}
     outputs:
       fmt_status: ${{ steps.fmt.outcome }}
       diff_exists: ${{ steps.fmt_commit.outputs.diff }}
@@ -121,7 +136,7 @@ jobs:
     needs:
       - terraform-fmt
     if: ${{ needs.terraform-fmt.outputs.diff_exists == 'false' }}
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.github_runner }}
     outputs:
       docs_status: ${{ steps.docs.outcome }}
       diff_exists: ${{ steps.docs.outputs.num_changed > 0 }}
@@ -162,7 +177,7 @@ jobs:
       - terraform-fmt
       - terraform-docs
     if: ${{ needs.terraform-fmt.outputs.diff_exists == 'false' && needs.terraform-docs.outputs.diff_exists == 'false' }}
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.github_runner }}
     outputs:
       lint_status: ${{ steps.lint.outcome }}
 
@@ -200,7 +215,7 @@ jobs:
       - terraform-docs
       - terraform-lint
     if: ${{ needs.terraform-fmt.outputs.diff_exists == 'false' && needs.terraform-docs.outputs.diff_exists == 'false' }}
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.github_runner }}
     outputs:
       security_status: ${{ steps.security.outcome }}
 
@@ -214,7 +229,7 @@ jobs:
       - name: Check For Examples
         run: |
           if [[ ! -d "./${{ inputs.terratest_examples_path }}" ]]; then
-            echo "could not find examples path '${{ inputs.terratest_examples_path }}' required for terratest"
+            echo "could not find required examples path '${{ inputs.terratest_examples_path }}' for terratest"
             exit 1
           fi
       
@@ -239,7 +254,7 @@ jobs:
       - terraform-lint
       - terraform-security
     if: ${{ needs.terraform-fmt.outputs.diff_exists == 'false' && needs.terraform-docs.outputs.diff_exists == 'false' }}
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.github_runner }}
     outputs:
       terratest_status: ${{ steps.terratest_summary.outcome }}
 
@@ -258,7 +273,7 @@ jobs:
         uses: actions/setup-go@v3
 
       - name: Get Dependencies
-        working-directory: ./test
+        working-directory: ${{ inputs.terratest_path }}
         run: |
           go get -v -t -d
           wget https://github.com/gruntwork-io/terratest/releases/download/v0.40.6/terratest_log_parser_linux_amd64
@@ -274,7 +289,7 @@ jobs:
 
       - name: Run Terratest
         id: terratest_run
-        working-directory: ./test
+        working-directory: ${{ inputs.terratest_path }}
         env:
           AWS_DEFAULT_REGION: ${{ secrets.TERRATEST_AWS_DEFAULT_REGION }}
           AWS_ACCESS_KEY_ID: ${{ secrets.TERRATEST_AWS_ACCESS_KEY_ID }}
@@ -287,11 +302,12 @@ jobs:
           go test -v -timeout 30m 2>&1 | tee >(./terratest_log_parser_linux_amd64)
           test ${PIPESTATUS[0]} -eq 0
           echo "./out/summary.log"
+        continue-on-error: true
       
       - name: Terratest Summary
         if: ${{ always() }}
         id: terratest_summary
-        working-directory: ./test
+        working-directory: ${{ inputs.terratest_path }}
         run: |
           echo '### TERRATEST SUMMARY :octocat:' >> $GITHUB_STEP_SUMMARY
           echo '${{ steps.terraform_lock_file.outputs.artifact_name }}' >> $GITHUB_STEP_SUMMARY
@@ -326,6 +342,11 @@ jobs:
           elif [[ $test_failed == true ]]; then
             exit 1
           fi
+        continue-on-error: true
+
+      - name: Terratest Outcome
+        if: ${{ steps.terratest_summary.outcome == 'failure' || steps.terratest_summary.outputs.exitcode == '1' }}
+        run: exit 1
 
   workflow-summary:
     needs:
@@ -334,7 +355,7 @@ jobs:
       - terraform-lint
       - terraform-security
       - terratest-run
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.github_runner }}
     if: ${{ always() }}
 
     steps:
