fix: adding error handling for custom script

diff --git a/.github/workflows/terraform-workspace.yml b/.github/workflows/terraform-workspace.yml
--- a/.github/workflows/terraform-workspace.yml
+++ b/.github/workflows/terraform-workspace.yml
@@ -86,7 +86,7 @@ jobs:
 
           if [[ -z "$WORKSPACE" || -z "$ORGANIZATION" ]]
           then
-            echo "could not get terraform cloud or enterprise organization and workspace name from '$BACKEND_FILE'"
+            echo "could not get terraform cloud/enterprise organization or workspace name from '$BACKEND_FILE'"
             exit 1
           fi
 
@@ -97,6 +97,13 @@ jobs:
           
           VERSION=$(cat workspace.txt | sed -rn 's|.*"terraform-version":"([0-9.]+)".*|\1|p')
           rm workspace.txt
+
+          if [[ -z "$VERSION" ]]
+          then
+            echo "could not get terraform version from terraform cloud/enterprise workspace '$WORKSPACE' in organization '$ORGANIZATION'"
+            exit 1
+          fi
+
           echo "::set-output name=terraform_version::${VERSION}"
 
       - name: Setup Terraform
