fix: consolidate and replacing terraform format action (#1)
* fix: replacing terraform format action

* fix: removing working directory for format

* fix: removing temporary file

* docs: updating usage example

* feat: adding check for submodules

* docs: adding included actions

* fix: updating terraform version check from TFE

* fix: adding error handling for custom script

* docs: updating inputs

* docs: adding comments and updating descriptions

diff --git a/.github/workflows/terraform-workspace.yml b/.github/workflows/terraform-workspace.yml
--- a/.github/workflows/terraform-workspace.yml
+++ b/.github/workflows/terraform-workspace.yml
@@ -4,17 +4,22 @@ on:
   workflow_call:
     inputs:
       tfe_hostname:
-        description: 'Hostname for terraform cloud or enterprise'
+        description: 'Hostname for terraform cloud/enterprise'
         default: 'app.terraform.io'
         required: false
         type: string
-      tfe_workspace_exec_mode:
-        description: 'tfe_workspace_exec_mode can be "cli" or "remote"'
-        default: 'cli'
+      tfe_backend_file:
+        description: 'Name of file where terraform cloud/enterprise backend configuration is stored (inside terraform_working_directory)'
+        default: 'backend.tf'
         required: false
         type: string
+      tfe_workspace_version:
+        description: 'Terraform version will be queried from the terraform cloud/enterprise workspace'
+        default: true
+        required: false
+        type: boolean
       terraform_version:
-        description: 'Terraform version will be ignored if tfe_workspace_exec_mode is "cli"'
+        description: 'Terraform version will be ignored if tfe_workspace_version is "true"'
         default: 'latest'
         required: false
         type: string
@@ -58,6 +63,7 @@ jobs:
   terraform-fmt:
     runs-on: ubuntu-latest
     outputs:
+      terraform_version: ${{ steps.workspace_curl.outputs.terraform_version }}
       fmt_status: ${{ steps.fmt.outcome }}
       diff_exists: ${{ steps.fmt_commit.outputs.diff }}
 
@@ -69,11 +75,55 @@ jobs:
           ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
           token: ${{ secrets.GHE_API_TOKEN }}
 
+      - name: Get Workspace Info
+        if: ${{ inputs.tfe_workspace_version }}
+        id: workspace_curl
+        env:
+          BACKEND_FILE: ${{ inputs.terraform_working_directory }}/${{ inputs.tfe_backend_file }}
+        run: |
+          if [[ ! -f $BACKEND_FILE ]]; then
+          then
+            echo "could not find terraform file '$BACKEND_FILE' with tfe backend configuration"
+            exit 1
+          fi
+
+          # get workspace name from backend file (backend 'remote' config block) via perl-regexp
+          WORKSPACE=$(grep -Pzo 'workspaces\W+\{\W+name\W+=\W+"\K\S+(?=")' $BACKEND_FILE)
+          # get organization name from backend file (backend 'remote' config block) via perl-regexp
+          ORGANIZATION=$(grep -Pzo 'backend\W+"remote"\W+\{\W+organization\W+=\W+"\K\S+(?=")' $BACKEND_FILE)
+
+          if [[ -z "$WORKSPACE" || -z "$ORGANIZATION" ]]
+          then
+            echo "could not get terraform cloud/enterprise organization or workspace name from '$BACKEND_FILE'"
+            exit 1
+          fi
+
+          # query terraform version from tfe workspace
+          curl \
+          --header "Authorization: Bearer ${{ secrets.TFE_API_TOKEN }}" \
+          --header "Content-Type: application/vnd.api+json" \
+          https://${{ inputs.tfe_hostname }}/api/v2/organizations/${ORGANIZATION}/workspaces/${WORKSPACE} > workspace.txt
+          
+          VERSION=$(cat workspace.txt | sed -rn 's|.*"terraform-version":"([0-9.]+)".*|\1|p')
+          rm workspace.txt
+
+          if [[ -z "$VERSION" ]]
+          then
+            echo "could not get terraform version from terraform cloud/enterprise workspace '$WORKSPACE' in organization '$ORGANIZATION'"
+            exit 1
+          fi
+          echo "::set-output name=terraform_version::${VERSION}"
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          # pseudo ternary expression: if tfe_workspace_version is 'true' then terraform_version will be same as workspace settings else manually defined version will be used
+          terraform_version: ${{ inputs.tfe_workspace_version && steps.workspace_curl.outputs.terraform_version || inputs.terraform_version }}
+
       - name: Terraform Format
         id: fmt
-        uses: dflook/terraform-fmt@v1
-        with:
-          path: ${{ inputs.terraform_working_directory }}
+        run: terraform fmt -recursive
+        working-directory: ${{ inputs.terraform_working_directory }}
 
       - name: Commit files
         id: fmt_commit
@@ -89,7 +139,7 @@ jobs:
           git diff-index --quiet HEAD || git commit -m "style(terraform fmt): format code" -a
 
       - name: Push changes
-        uses: ad-m/github-push-action@master
+        uses: ad-m/github-push-action@v0.6.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           # pseudo ternary expression: if github event name is 'pull_request' then push to pull request branch else push to main branch
@@ -194,7 +244,6 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       tfe_run_url: ${{ steps.tfe_run_url.outputs.url }}
-      terraform_version: ${{ steps.workspace_curl.outputs.terraform_version }}
       init_status: ${{ steps.init.outcome }}
       plan_status: ${{ steps.plan.outputs.exitcode == '1' || steps.plan.outcome }}
 
@@ -209,26 +258,11 @@ jobs:
           # pseudo ternary expression: if github event name is 'pull_request' then checkout pull request branch else checkout main branch
           ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
 
-      - name: Get Workspace Info
-        if: ${{ inputs.tfe_workspace_exec_mode == 'cli' }}
-        id: workspace_curl
-        run: |
-          WORKSPACE=$(cat backend.tf | sed -rn 's/\s+name = "(\S+)"/\1/p')
-          ORGANIZATION=$(cat backend.tf | sed -rn 's/\s+organization = "(\S+)"/\1/p')
-
-          curl \
-          --header "Authorization: Bearer ${{ secrets.TFE_API_TOKEN }}" \
-          --header "Content-Type: application/vnd.api+json" \
-          https://${{ inputs.tfe_hostname }}/api/v2/organizations/${ORGANIZATION}/workspaces/${WORKSPACE} > workspace.txt
-          
-          VERSION=$(cat workspace.txt | sed -rn 's/.*"terraform-version":"([0-9.]+)".*/\1/p')
-          echo "::set-output name=terraform_version::${VERSION}"
-
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
-          # pseudo ternary expression: if tfe_workspace_exec_mode is 'cli' then terraform_version will be same as workspace settings else manually defined version will be used
-          terraform_version: ${{ inputs.tfe_workspace_exec_mode == 'cli' && steps.workspace_curl.outputs.terraform_version || inputs.terraform_version }}
+          # pseudo ternary expression: if tfe_workspace_version is 'true' then terraform_version will be same as workspace settings else manually defined version will be used
+          terraform_version: ${{ inputs.tfe_workspace_version && needs.terraform-fmt.outputs.terraform_version || inputs.terraform_version }}
           terraform_wrapper: true
           cli_config_credentials_hostname: ${{ inputs.tfe_hostname }}
           cli_config_credentials_token: ${{ secrets.TFE_API_TOKEN }}
@@ -274,8 +308,8 @@ jobs:
         uses: marocchino/sticky-pull-request-comment@v2
         env:
           TFE_RUN_URL: ${{ needs.terraform-run.outputs.tfe_run_url }}
-          # pseudo ternary expression: if tfe_workspace_exec_mode is 'cli' then terraform_version will be same as workspace settings else manually defined version will be used
-          TERRAFORM_VERSION: ${{ inputs.tfe_workspace_exec_mode == 'cli' && needs.terraform-run.outputs.terraform_version || inputs.terraform_version }}
+          # pseudo ternary expression: if tfe_workspace_version is 'true' then terraform_version will be same as workspace settings else manually defined version will be used
+          TERRAFORM_VERSION: ${{ inputs.tfe_workspace_version && needs.terraform-run.outputs.terraform_version || inputs.terraform_version }}
           TF_FMT_RESULT: ${{ fromJSON('[":white_check_mark:", ":x:"]')[needs.terraform-fmt.outputs.fmt_status != 'success'] }}
           TF_DOCS_RESULT: ${{ fromJSON('[":white_check_mark:", ":x:"]')[needs.terraform-docs.outputs.docs_status != 'success'] }}
           TF_LINT_RESULT: ${{ fromJSON('[":white_check_mark:", ":x:"]')[needs.terraform-lint.outputs.lint_status != 'success'] }}
